"use strict";Object.defineProperty(exports, "__esModule", {value: true});require('./chunk-S65R2BUY.js');
const URI_SDX_GENERATE_FOLDER = `/.sdx-gen`;
const URI_SDX_GENERATE_SHACL_FOLDER = `${URI_SDX_GENERATE_FOLDER}/shacl`;
const URI_SDX_GENERATE_GRAPHQL_FOLDER = `${URI_SDX_GENERATE_FOLDER}/graphql`;
const URI_SDX_GENERATE_GRAPHQL_SCHEMA = `${URI_SDX_GENERATE_GRAPHQL_FOLDER}/schema.graphqls`;





exports.URI_SDX_GENERATE_FOLDER = URI_SDX_GENERATE_FOLDER; exports.URI_SDX_GENERATE_GRAPHQL_FOLDER = URI_SDX_GENERATE_GRAPHQL_FOLDER; exports.URI_SDX_GENERATE_GRAPHQL_SCHEMA = URI_SDX_GENERATE_GRAPHQL_SCHEMA; exports.URI_SDX_GENERATE_SHACL_FOLDER = URI_SDX_GENERATE_SHACL_FOLDER;
