import "./chunk-G42LTC7K.mjs";
const URI_SDX_GENERATE_FOLDER = `/.sdx-gen`;
const URI_SDX_GENERATE_SHACL_FOLDER = `${URI_SDX_GENERATE_FOLDER}/shacl`;
const URI_SDX_GENERATE_GRAPHQL_FOLDER = `${URI_SDX_GENERATE_FOLDER}/graphql`;
const URI_SDX_GENERATE_GRAPHQL_SCHEMA = `${URI_SDX_GENERATE_GRAPHQL_FOLDER}/schema.graphqls`;
export {
  URI_SDX_GENERATE_FOLDER,
  URI_SDX_GENERATE_GRAPHQL_FOLDER,
  URI_SDX_GENERATE_GRAPHQL_SCHEMA,
  URI_SDX_GENERATE_SHACL_FOLDER
};
