declare const URI_SDX_GENERATE_FOLDER = "/.sdx-gen";
declare const URI_SDX_GENERATE_SHACL_FOLDER: string;
declare const URI_SDX_GENERATE_GRAPHQL_FOLDER: string;
declare const URI_SDX_GENERATE_GRAPHQL_SCHEMA: string;

export { URI_SDX_GENERATE_FOLDER, URI_SDX_GENERATE_GRAPHQL_FOLDER, URI_SDX_GENERATE_GRAPHQL_SCHEMA, URI_SDX_GENERATE_SHACL_FOLDER };
